import Banner from "@/components/Banner"
import Footer from "@/components/Footer"
import Header from "@/components/Header"
export const metadata = {
  title: 'Blogging Wizard',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      <body suppressHydrationWarning={true}>
        <Header/>
        <Banner/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
