import Header from '@/components/Header'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Banner from '@/components/Banner'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  
  title: 'Geeky Wizard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
          <link rel="icon" href="/gw.png" sizes="any" />
      </Head>
      <body className=" max-w-7xl mx-auto">
        <Header/>
        <Banner/>
        {children}
      </body>
    </html>
  )
}
